name: kelp_se_image_converter
description: Kelp's SE image to text converter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: "^0.12.1"
  bitmap: "^0.0.6"
  file_picker: "^2.1.5"
  mime: "^0.9.7"
  flex_color_picker: "^1.1.3"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

